# Generated by Django 4.0.2 on 2022-03-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfinfo',
            name='college',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
